const Bar = [
    {
        "value":"/tradeManagement",
        "name":"订单管理",
        "sub":[
            {
                "value":"/tradeManagement",
                "name":"订单管理",
            },
            {
                "value":"/sidWithSend",
                "name":"导入单号发货",
            },
            {
                "value":"/tradeManagement",
                "name":"退款管理",
            },
            {
                "value":"/tradeManagement",
                "name":"批量转账",
            },
        ],
    },
    {
        "value":"/batchPrint",
        "name":"打单发货",
        "sub":[
            {
                "value":"/tradeManagement",
                "name":"打单发货",
            },
            {
                "value":"/tradeManagement",
                "name":"自由打印",
            },
            {
                "value":"/tradeManagement",
                "name":"打印底单",
            },
            {
                "value":"/tradeManagement",
                "name":"打印设置",
            },
            {
                "value":"/tradeManagement",
                "name":"模板设置",
            },
            {
                "value":"/tradeManagement",
                "name":"电子面单",
            },
            {
                "value":"/tradeManagement",
                "name":"打印日志",
            },
        ]
    },
    {
        "value":"/customPrint",
        "name":"自由打印",
        "sub":[
            {
                "value":"/tradeManagement",
                "name":"打单发货",
            },
            {
                "value":"/tradeManagement",
                "name":"自由打印",
            },
            {
                "value":"/tradeManagement",
                "name":"打印底单",
            },
            {
                "value":"/tradeManagement",
                "name":"打印设置",
            },
            {
                "value":"/tradeManagement",
                "name":"模板设置",
            },
            {
                "value":"/tradeManagement",
                "name":"电子面单",
            },
            {
                "value":"/tradeManagement",
                "name":"打印日志",
            },
        ]
    },
    {
        "value":"/intercept",
        "name":"差评拦截",
        "sub":[
            {
                "value":"/tradeManagement",
                "name":"拦截概况",
            },
            {
                "value":"/tradeManagement",
                "name":"拦截日志",
            },
            {
                "value":"/tradeManagement",
                "name":"操作日志",
            },
        ]
    },
    {
        "value":"/autoRate",
        "name":"自动评价",
        "sub":[
            {
                "value":"/tradeManagement",
                "name":"评价设置",
            },
            {
                "value":"/tradeManagement",
                "name":"评价日志",
            }
        ]
    },
    {
        "value":"/batchRate",
        "name":"批量批量",
        "sub":[
            {
                "value":"/tradeManagement",
                "name":"评价管理",
            },
            {
                "value":"/tradeManagement",
                "name":"批量评价",
            },
        ]
    },
    {
        "value":"/rateManagement",
        "name":"评价管理",
        "sub":[
            {
                "value":"/tradeManagement",
                "name":"评价管理",
            },
            {
                "value":"/tradeManagement",
                "name":"批量评价",
            },
        ]
    },
    {
        "value":"/smsCare",
        "name":"短信关怀",
        "sub":[
            {
                "value":"/tradeManagement",
                "name":"短信关怀",
            },
        ]
    },
    {
        "value":"/settings",
        "name":"设置",
        "sub":[
            {
                "value":"/tradeManagement",
                "name":"发货设置",
            },
            {
                "value":"/tradeManagement",
                "name":"打印设置",
            },
            {
                "value":"/tradeManagement",
                "name":"短语设置",
            },
            {
                "value":"/tradeManagement",
                "name":"商品设置",
            },
            {
                "value":"/tradeManagement",
                "name":"订单检测设置",
            },
            {
                "value":"/tradeManagement",
                "name":"系统设置",
            },
            {
                "value":"/tradeManagement",
                "name":"电子面单",
            },
            {
                "value":"/tradeManagement",
                "name":"操作日志",
            },
        ],
    },
];
export default  Bar;
